# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a352745bf46acebdb45169cfc1d387921ffeb41921639cb6ae45751bd69eb5a7aa67b0a68670c1ffd8eb3b438ccd474e4ac38a0ba199972565556365f23a661

test:
  secret_key_base: d170ca112f182894731c1be1bafd320a7dfb62ced7d9edc3bc11f85c4db9ca59a84eaa27af4cfa4699f767d6961f5772e3501444d855b2c0c4c18fc1a4fae83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
